### ISSUE TITLE
question about annotation.pl

### ISSUE THREAD

**Issue by hemingwang** [junchaoshi/sports1.0#2]
Hi Junchao,
I am ran the sports.pl and produce the results. But when I run the annotation.pl, I meet the wrong:

Can't open '/smallrna/qi/out.fa': No such file or directory at annotation.pl line 33.

my sports.pl file is in the "/smallrna/qi/",named "out". The "out" file contain "1_S1_trimmed","processing_report","sh_file" and "run_this.sh"

I am looking forward to your reply!

Best wishes!
heming wang

**Comment by junchaoshi** [comment]
Hi,
Couly you upload your commond and head of your fq file? THX

**Comment by junchaoshi** [comment]
Hi,
Couly you upload your commond and head of your fq file? THX

**Comment by hemingwang** [comment]
Hi Junchao,
my code is:
sports.pl -i ~/smallrna/S1_trimmed.fastq -p 12 -a -x GTTCAGAGTTCTACAGTCCGACGATC -y AGATCGGAAGAGCACACGTCT -g ~/smallrna/qi/Homo_sapiens/UCSC/hg38/Sequence/BowtieIndex/genome -m ~/smallrna/qi/Homo_sapiens/miRBase_21/miRBase_21-hsa -r ~/smallrna/qi/Homo_sapiens/rRNAdb/human_rRNA -t ~/smallrna/qi/Homo_sapiens/GtRNAdb/hg19-tRNAs -w ~/smallrna/qi/Homo_sapiens/piRBase/piR_human -e ~/smallrna/qi/Homo_sapiens/Ensembl/Homo_sapiens.GRCh38.ncrna -f ~/smallrna/qi/Homo_sapiens/Rfam_12.3/Rfam-12.3-human -o ~/smallrna/qi/out -k

head of the fq:
@E00515:299:HJY52CCXY:4:1101:2209:1801 1:N:0:ATCACGAT
CTCGCTGCGATCTATTGAAAGTCAGCCCTCGACGCAAGGGTTTGTA
+
<AAFA<AFJ--AAJF<JJFJFJJAF7FFJJAFA-FAF-FFFF7F-7
@E00515:299:HJY52CCXY:4:1101:3488:1801 1:N:0:ATCACGAT
AGACTGTGTTTT
+
<AAFFJJJJJFJ
@E00515:299:HJY52CCXY:4:1101:4584:1801 1:N:0:ATCACGAT
CTCGCTGCGATCTATTGAAAGTCAGCCCTCGACACAAGGGTTTGT


Best wishes!
heming wang

**Comment by junchaoshi** [comment]
It looks like your fastq file is already trimmed so that -a -x -y is not necessary. Could you run it again and theck the processing report to see what exact happens?

**Comment by hemingwang** [comment]
Thanks for your patience helping me!
I run it again.
