### ISSUE TITLE
Change the order of Databases

### ISSUE THREAD

**Issue by ConYel** [junchaoshi/sports1.0#3]
Dear Junchaoshi,
Thanks for this great software tool, I would like to know if there is a possibility to change the order of
databases annotation.
I would like to annotate piRNAdb after miRNA if it is possible.
I'm aware of the publication 

> Non-coding RNA fragments account for the majority of annotated piRNAs expressed in somatic non-gonadal tissues

but I would like to have the option for that.

**Comment by ConYel** [comment]
Yes, I know about this issue, but piRBase has been updated to a second version with a lot more sequences. 
That's is why I wanted to use it before rRNA/tRNA databases.

**Comment by junchaoshi** [comment]
It's easy to compare the difference: first just annotate miRNA and piRNA and do it again with other databases to see the difference. A lot more sequences didn't mean they are good.

**Comment by ConYel** [comment]
I know that this doesn't improve the quality of the sequences, anyway I will use it with and without the other databases.
Thank you

**Comment by junchaoshi** [comment]
No problem. It will be great if you can compare and let me know the difference so that I can consider if it is necessary to put the function in the next version.

**Comment by ConYel** [comment]
Another thing that I would find very useful is that if it could have a function that downloads all new databases as the [unitas](http://www.smallrnagroup.uni-mainz.de/software/unitas_documentation_1.6.1.pdf) web tool does!

**Comment by junchaoshi** [comment]
Good point! The link is here: https://ncrnainfo-my.sharepoint.com/:f:/g/personal/sports_ncrna_info/EvZP50IfGFRJlNJwZRujI00BM-CP_w7gITsv8iU45m1rxQ?e=Pk89b9.

**Comment by ConYel** [comment]
> 
> 
> Good point! The link is here: https://ncrnainfo-my.sharepoint.com/:f:/g/personal/sports_ncrna_info/EvZP50IfGFRJlNJwZRujI00BM-CP_w7gITsv8iU45m1rxQ?e=Pk89b9.

Are these the latest databases versions? 
Could you check also the GtRNAdb, you have uploaded the version of  hg19-tRNAs with the hg38 genome, so it would be better if you provide the hg38-tRNA version of GtRNAdb.

**Comment by junchaoshi** [comment]
all the database are generated by bowtie1.0 so you can easily customize the database by youself.

**Comment by junchaoshi** [comment]
gtrnadb only provided hg19 trna database for now.

**Comment by ConYel** [comment]
Isn't this one for hg38?
http://gtrnadb.ucsc.edu/GtRNAdb2/genomes/eukaryota/Hsapi38/

**Comment by junchaoshi** [comment]
good to know, it doesn't show in the homepage.
