### ISSUE TITLE
Summaries don't sumup

### ISSUE THREAD

**Issue by ConYel** [junchaoshi/sports1.0#4]
I was checking some resulted summaries and while I was trying to find the sum up of  "matched to genome reads" were correct and I found that it is different than the one it is typed in the "summary.txt".
Could you have a look on that?
[random2_summary.txt](https://github.com/junchaoshi/sports1.0/files/2746396/random2_summary.txt)
[random1_summary.txt](https://github.com/junchaoshi/sports1.0/files/2746397/random1_summary.txt)

These files have been produced from original summaries files using grep for only the "Match_Genome" entries

**Comment by junchaoshi** [comment]
two thing you need to pay attetion: GtRNAdb-tRNA_Match_Genome contains the subtype of tRNA so the subtype reads will not sum up; sometimes the reads are rounded up particularly for those mulit-loci RNAs.

**Comment by ConYel** [comment]
Ok thanks, still there is a miscalculation of ~11 reads

**Comment by junchaoshi** [comment]
the second point as I metioned. Please read carefully.
