### ISSUE TITLE
rRNA output systematically emtpy

### ISSUE THREAD

**Issue by plger** [junchaoshi/sports1.0#6]
Hi,
Thanks for the great tool.
I'm using your Mus Musculus annotation (and `-r $ref/rRNA_db/mouse_rRNA`) with standard truseq small rna data, and there's never any overlap detected with `rRNA_db` annotation: the `_processed/*_output_rRNA_*` are empty (but there), and in the `_result/*_summary.txt` file there are (many) reads assigned to `ensembl-rRNA` and `Rfam-rRNA`, but nothing from rRNA_db. The `processing_report/*.txt` is empty in that section, and has no other indication except plotting errors at the end, i.e.:
```
match to rRNA database

match to tRNA database

[...]

generating graph
Error: No enough input parameters!
Execution halted
Error: No enough input parameters!
Execution halted
```

It seems difficult to imagine that there would really be no trace of the 4S/5S/etc (across many samples)...
Looking at the different annotation subfolders, I noticed that while all annotations have a single bowtie index (i.e. prefix), rRNA_db has several - could the problem stem from this?

Any pointer on how to debug this would be appreciated.

**Comment by junchaoshi** [comment]
Hi plger,

Yes, most datasets should contain rRNAs. And the rRNA annotation fold indeed contains several rRNA bowtie indexes for rRNA annotation strategy. The error showed in the report means you used the -r parameter but no data generated. However, according to your description, I can only suggest you redownload the database.

**Comment by plger** [comment]
Hi,
don't know why I missed it yesterday:
in your documentation it says to use `-r /<your_defined_address>/Mus_musculus/rRNA_db/mouse_rRNA`, but actually in the annotation you created the folder is `rRNAdb`, not `rRNA_db` (you might want to change the readme!). Then it works like a charm.
Thanks,

**Comment by junchaoshi** [comment]
Hi plger,

Good to know you have debuged.
